/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AttendantRouteImport } from './routes/attendant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AttendantIndexRouteImport } from './routes/attendant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RiderSettingsRouteImport } from './routes/rider.settings'
import { Route as RiderHistoryRouteImport } from './routes/rider.history'
import { Route as RiderEarningsRouteImport } from './routes/rider.earnings'
import { Route as RiderDeliveriesRouteImport } from './routes/rider.deliveries'
import { Route as DashboardTrackingRouteImport } from './routes/dashboard.tracking'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardShipmentsRouteImport } from './routes/dashboard.shipments'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendantRoute = AttendantRouteImport.update({
  id: '/attendant',
  path: '/attendant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AttendantIndexRoute = AttendantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendantRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrackRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const RiderSettingsRoute = RiderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RiderRoute,
} as any)
const RiderHistoryRoute = RiderHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RiderRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRoute,
} as any)
const RiderDeliveriesRoute = RiderDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => RiderRoute,
} as any)
const DashboardTrackingRoute = DashboardTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShipmentsRoute = DashboardShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendant': typeof AttendantRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/rider': typeof RiderRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/track': typeof TrackRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/rider/deliveries': typeof RiderDeliveriesRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/settings': typeof RiderSettingsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/track/$id': typeof TrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/attendant/': typeof AttendantIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/rider/deliveries': typeof RiderDeliveriesRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/settings': typeof RiderSettingsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/track/$id': typeof TrackIdRoute
  '/admin': typeof AdminIndexRoute
  '/attendant': typeof AttendantIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/rider': typeof RiderIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendant': typeof AttendantRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/rider': typeof RiderRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/track': typeof TrackRouteWithChildren
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/rider/deliveries': typeof RiderDeliveriesRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/settings': typeof RiderSettingsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/track/$id': typeof TrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/attendant/': typeof AttendantIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/attendant'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/quote'
    | '/rider'
    | '/services'
    | '/signup'
    | '/track'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/finance'
    | '/admin/fleet'
    | '/admin/orders'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/zones'
    | '/dashboard/bookings'
    | '/dashboard/invoices'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/support'
    | '/dashboard/tracking'
    | '/rider/deliveries'
    | '/rider/earnings'
    | '/rider/history'
    | '/rider/settings'
    | '/services/$slug'
    | '/track/$id'
    | '/admin/'
    | '/attendant/'
    | '/dashboard/'
    | '/rider/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/quote'
    | '/signup'
    | '/track'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/finance'
    | '/admin/fleet'
    | '/admin/orders'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/zones'
    | '/dashboard/bookings'
    | '/dashboard/invoices'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/support'
    | '/dashboard/tracking'
    | '/rider/deliveries'
    | '/rider/earnings'
    | '/rider/history'
    | '/rider/settings'
    | '/services/$slug'
    | '/track/$id'
    | '/admin'
    | '/attendant'
    | '/dashboard'
    | '/rider'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/attendant'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/quote'
    | '/rider'
    | '/services'
    | '/signup'
    | '/track'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/finance'
    | '/admin/fleet'
    | '/admin/orders'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/zones'
    | '/dashboard/bookings'
    | '/dashboard/invoices'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/support'
    | '/dashboard/tracking'
    | '/rider/deliveries'
    | '/rider/earnings'
    | '/rider/history'
    | '/rider/settings'
    | '/services/$slug'
    | '/track/$id'
    | '/admin/'
    | '/attendant/'
    | '/dashboard/'
    | '/rider/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttendantRoute: typeof AttendantRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  QuoteRoute: typeof QuoteRoute
  RiderRoute: typeof RiderRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
  TrackRoute: typeof TrackRouteWithChildren
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendant': {
      id: '/attendant'
      path: '/attendant'
      fullPath: '/attendant'
      preLoaderRoute: typeof AttendantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/attendant/': {
      id: '/attendant/'
      path: '/'
      fullPath: '/attendant/'
      preLoaderRoute: typeof AttendantIndexRouteImport
      parentRoute: typeof AttendantRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/rider/settings': {
      id: '/rider/settings'
      path: '/settings'
      fullPath: '/rider/settings'
      preLoaderRoute: typeof RiderSettingsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/history': {
      id: '/rider/history'
      path: '/history'
      fullPath: '/rider/history'
      preLoaderRoute: typeof RiderHistoryRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/deliveries': {
      id: '/rider/deliveries'
      path: '/deliveries'
      fullPath: '/rider/deliveries'
      preLoaderRoute: typeof RiderDeliveriesRouteImport
      parentRoute: typeof RiderRoute
    }
    '/dashboard/tracking': {
      id: '/dashboard/tracking'
      path: '/tracking'
      fullPath: '/dashboard/tracking'
      preLoaderRoute: typeof DashboardTrackingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shipments': {
      id: '/dashboard/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof DashboardShipmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AttendantRouteChildren {
  AttendantIndexRoute: typeof AttendantIndexRoute
}

const AttendantRouteChildren: AttendantRouteChildren = {
  AttendantIndexRoute: AttendantIndexRoute,
}

const AttendantRouteWithChildren = AttendantRoute._addFileChildren(
  AttendantRouteChildren,
)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShipmentsRoute: typeof DashboardShipmentsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTrackingRoute: typeof DashboardTrackingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShipmentsRoute: DashboardShipmentsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTrackingRoute: DashboardTrackingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RiderRouteChildren {
  RiderDeliveriesRoute: typeof RiderDeliveriesRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderHistoryRoute: typeof RiderHistoryRoute
  RiderSettingsRoute: typeof RiderSettingsRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderDeliveriesRoute: RiderDeliveriesRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderHistoryRoute: RiderHistoryRoute,
  RiderSettingsRoute: RiderSettingsRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface TrackRouteChildren {
  TrackIdRoute: typeof TrackIdRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackIdRoute: TrackIdRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AttendantRoute: AttendantRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  QuoteRoute: QuoteRoute,
  RiderRoute: RiderRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
  TrackRoute: TrackRouteWithChildren,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
